title: Homebridge Camera FFmpeg
author: David Maher
description: A place to store the tested configurations created by users of Homebridge Camera FFmpeg
baseurl: "/homebridge-camera-ffmpeg"
url: "https://sunoo.github.io"
github_username:  Sunoo

markdown: CommonMarkGhPages
theme: minima

collections:
  configs:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "configs"
    values:
      layout: "config"
